# Gradle optimization flags
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdkWarning=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
