// File generated by flutterfire configure
// This file is auto-generated. Do not edit manually.
// Run: flutterfire configure --project=safe-mother-malawi

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For Android
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    // For iOS
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    // For Web (default for web platform)
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmB-FDoPYNTBJ-WxOJe0420c6ioJVjey4',
    appId: '1:364677454045:android:abcdefghijklmnopqrst',
    messagingSenderId: '364677454045',
    projectId: 'fir-mobile-app-34535',
    storageBucket: 'fir-mobile-app-34535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmB-FDoPYNTBJ-WxOJe0420c6ioJVjey4',
    appId: '1:364677454045:ios:abcdefghijklmnopqrst',
    messagingSenderId: '364677454045',
    projectId: 'fir-mobile-app-34535',
    storageBucket: 'fir-mobile-app-34535.firebasestorage.app',
    iosBundleId: 'com.example.safemothermalawi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmB-FDoPYNTBJ-WxOJe0420c6ioJVjey4',
    appId: '1:364677454045:web:6b858004f58d0656b8e334',
    messagingSenderId: '364677454045',
    projectId: 'fir-mobile-app-34535',
    authDomain: 'fir-mobile-app-34535.firebaseapp.com',
    storageBucket: 'fir-mobile-app-34535.firebasestorage.app',
    measurementId: 'G-YET8NZC3Y2',
  );
}
