// File generated by flutterfire configure
// This file is auto-generated. Do not edit manually.
// Run: flutterfire configure --project=safe-mother-malawi

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // For Android
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    // For iOS
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    // For Web
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:android:abcdefghijklmnopqrst',
    messagingSenderId: '123456789',
    projectId: 'safe-mother-malawi',
    storageBucket: 'safe-mother-malawi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:ios:abcdefghijklmnopqrst',
    messagingSenderId: '123456789',
    projectId: 'safe-mother-malawi',
    storageBucket: 'safe-mother-malawi.appspot.com',
    iosBundleId: 'com.example.safemothermalawi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:123456789:web:abcdefghijklmnopqrst',
    messagingSenderId: '123456789',
    projectId: 'safe-mother-malawi',
    authDomain: 'safe-mother-malawi.firebaseapp.com',
    storageBucket: 'safe-mother-malawi.appspot.com',
  );
}
